/**
 * Game Development Service
 * Provides proper game development capabilities using Phaser.js and other frameworks
 */

import Phaser from 'phaser';

class GameDevelopmentService {
  constructor() {
    this.gameInstances = new Map();
    this.gameTemplates = {
      'temple-run': this.generateTempleRunTemplate.bind(this),
      'endless-runner': this.generateEndlessRunnerTemplate.bind(this),
      'platformer': this.generatePlatformerTemplate.bind(this),
      'puzzle': this.generatePuzzleTemplate.bind(this),
      'arcade': this.generateArcadeTemplate.bind(this)
    };
  }

  /**
   * Generate a complete game based on the requested type
   */
  generateGame(gameType, options = {}) {

    const template = this.gameTemplates[gameType];
    if (!template) {
      throw new Error(`Unsupported game type: ${gameType}`);
    }

    return template(options);
  }

  /**
   * Generate Temple Run game using Phaser.js
   */
  generateTempleRunTemplate(options = {}) {
    const gameConfig = {
      type: Phaser.AUTO,
      width: 800,
      height: 600,
      physics: {
        default: 'arcade',
        arcade: {
          gravity: { y: 0 },
          debug: false
        }
      },
      scene: {
        preload: this.templeRunPreload.bind(this),
        create: this.templeRunCreate.bind(this),
        update: this.templeRunUpdate.bind(this)
      }
    };

    return {
      framework: 'phaser',
      config: gameConfig,
      files: this.generateTempleRunFiles(gameConfig),
      instructions: this.getTempleRunInstructions()
    };
  }

  /**
   * Generate Temple Run game files
   */
  generateTempleRunFiles(config) {
    return {
      'index.html': this.generateTempleRunHTML(config),
      'game.js': this.generateTempleRunJS(config),
      'style.css': this.generateTempleRunCSS(),
      'package.json': this.generateGamePackageJson(),
      'README.md': this.generateTempleRunREADME()
    };
  }

  /**
   * Generate HTML file for Temple Run
   */
  generateTempleRunHTML(config) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Temple Run - DreamBuild Game</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.70.0/dist/phaser.min.js"></script>
</head>
<body>
    <div id="game-container">
        <div id="game-ui">
            <div class="score">Score: <span id="score">0</span></div>
            <div class="lives">Lives: <span id="lives">3</span></div>
            <div class="distance">Distance: <span id="distance">0</span></div>
        </div>
        <div id="game-canvas"></div>
        <div id="game-over" class="hidden">
            <h2>Game Over!</h2>
            <p>Final Score: <span id="final-score">0</span></p>
            <button id="restart-btn">Play Again</button>
        </div>
        <div id="start-screen">
            <h1>Temple Run</h1>
            <p>Use A/D or Arrow Keys to switch lanes</p>
            <p>Use W or Space to jump</p>
            <p>Use S or Down Arrow to slide</p>
            <button id="start-btn">Start Game</button>
        </div>
    </div>
    <script src="game.js"></script>
</body>
</html>`;
  }

  /**
   * Generate JavaScript file for Temple Run
   */
  generateTempleRunJS(config) {
    return `// Temple Run Game - Generated by DreamBuild
class TempleRunGame extends Phaser.Scene {
    constructor() {
        super({ key: 'TempleRunGame' });
        this.player = null;
        this.obstacles = [];
        this.coins = [];
        this.score = 0;
        this.lives = 3;
        this.distance = 0;
        this.speed = 200;
        this.isGameOver = false;
        this.isJumping = false;
        this.isSliding = false;
        this.currentLane = 1; // 0, 1, 2
        this.laneWidth = 200;
        this.lanePositions = [150, 400, 650];
    }

    preload() {
        // Create simple colored rectangles for game objects
        this.load.image('player', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==');
        this.load.image('obstacle', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==');
        this.load.image('coin', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==');
    }

    create() {
        // Create background
        this.add.rectangle(400, 300, 800, 600, 0x87CEEB);
        
        // Create ground
        this.add.rectangle(400, 550, 800, 100, 0x8B4513);
        
        // Create lanes
        for (let i = 0; i < 3; i++) {
            this.add.rectangle(this.lanePositions[i], 300, 10, 600, 0x654321);
        }

        // Create player
        this.player = this.add.rectangle(
            this.lanePositions[this.currentLane], 
            450, 
            40, 
            40, 
            0xFFD700
        );
        this.player.setStrokeStyle(2, 0xFFA500);

        // Create input handlers
        this.cursors = this.input.keyboard.createCursorKeys();
        this.wasd = this.input.keyboard.addKeys('W,S,A,D,SPACE');

        // Create obstacle spawner
        this.obstacleTimer = this.time.addEvent({
            delay: 2000,
            callback: this.spawnObstacle,
            callbackScope: this,
            loop: true
        });

        // Create coin spawner
        this.coinTimer = this.time.addEvent({
            delay: 1500,
            callback: this.spawnCoin,
            callbackScope: this,
            loop: true
        });

        // Start screen
        this.startScreen = document.getElementById('start-screen');
        this.gameOverScreen = document.getElementById('game-over');
        this.startBtn = document.getElementById('start-btn');
        this.restartBtn = document.getElementById('restart-btn');

        this.startBtn.addEventListener('click', () => {
            this.startScreen.classList.add('hidden');
            this.startGame();
        });

        this.restartBtn.addEventListener('click', () => {
            this.gameOverScreen.classList.add('hidden');
            this.restartGame();
        });

        // Update UI
        this.updateUI();
    }

    update() {
        if (this.isGameOver) return;

        this.handleInput();
        this.updateObstacles();
        this.updateCoins();
        this.updateDistance();
        this.checkCollisions();
    }

    handleInput() {
        // Lane switching
        if (Phaser.Input.Keyboard.JustDown(this.cursors.left) || 
            Phaser.Input.Keyboard.JustDown(this.wasd.A)) {
            this.switchLane(-1);
        }
        if (Phaser.Input.Keyboard.JustDown(this.cursors.right) || 
            Phaser.Input.Keyboard.JustDown(this.wasd.D)) {
            this.switchLane(1);
        }

        // Jumping
        if ((Phaser.Input.Keyboard.JustDown(this.cursors.up) || 
             Phaser.Input.Keyboard.JustDown(this.wasd.W) ||
             Phaser.Input.Keyboard.JustDown(this.wasd.SPACE)) && !this.isJumping) {
            this.jump();
        }

        // Sliding
        if ((Phaser.Input.Keyboard.JustDown(this.cursors.down) || 
             Phaser.Input.Keyboard.JustDown(this.wasd.S)) && !this.isSliding) {
            this.slide();
        }
    }

    switchLane(direction) {
        this.currentLane = Phaser.Math.Clamp(this.currentLane + direction, 0, 2);
        this.tweens.add({
            targets: this.player,
            x: this.lanePositions[this.currentLane],
            duration: 200,
            ease: 'Power2'
        });
    }

    jump() {
        if (this.isJumping) return;
        
        this.isJumping = true;
        this.player.y -= 50;
        
        this.tweens.add({
            targets: this.player,
            y: 450,
            duration: 500,
            ease: 'Power2',
            onComplete: () => {
                this.isJumping = false;
            }
        });
    }

    slide() {
        if (this.isSliding) return;
        
        this.isSliding = true;
        this.player.height = 20;
        this.player.y += 20;
        
        this.tweens.add({
            targets: this.player,
            height: 40,
            y: 450,
            duration: 400,
            ease: 'Power2',
            onComplete: () => {
                this.isSliding = false;
            }
        });
    }

    spawnObstacle() {
        const lane = Phaser.Math.Between(0, 2);
        const obstacle = this.add.rectangle(
            this.lanePositions[lane],
            -50,
            30,
            60,
            0x8B4513
        );
        obstacle.lane = lane;
        obstacle.type = Phaser.Math.Between(0, 1) ? 'high' : 'low';
        
        if (obstacle.type === 'low') {
            obstacle.height = 40;
            obstacle.y = 510;
        }
        
        this.obstacles.push(obstacle);
    }

    spawnCoin() {
        const lane = Phaser.Math.Between(0, 2);
        const coin = this.add.circle(
            this.lanePositions[lane],
            -50,
            15,
            0xFFD700
        );
        coin.lane = lane;
        coin.setStrokeStyle(2, 0xFFA500);
        
        this.coins.push(coin);
    }

    updateObstacles() {
        this.obstacles.forEach((obstacle, index) => {
            obstacle.y += this.speed * 0.016;
            
            if (obstacle.y > 650) {
                obstacle.destroy();
                this.obstacles.splice(index, 1);
            }
        });
    }

    updateCoins() {
        this.coins.forEach((coin, index) => {
            coin.y += this.speed * 0.016;
            
            if (coin.y > 650) {
                coin.destroy();
                this.coins.splice(index, 1);
            }
        });
    }

    updateDistance() {
        this.distance += this.speed * 0.016;
        this.speed = Math.min(400, 200 + this.distance * 0.1);
    }

    checkCollisions() {
        // Check obstacle collisions
        this.obstacles.forEach((obstacle, index) => {
            if (obstacle.lane === this.currentLane && 
                Phaser.Geom.Rectangle.Overlaps(this.player.getBounds(), obstacle.getBounds())) {
                this.hitObstacle();
                obstacle.destroy();
                this.obstacles.splice(index, 1);
            }
        });

        // Check coin collections
        this.coins.forEach((coin, index) => {
            if (coin.lane === this.currentLane && 
                Phaser.Geom.Rectangle.Overlaps(this.player.getBounds(), coin.getBounds())) {
                this.collectCoin();
                coin.destroy();
                this.coins.splice(index, 1);
            }
        });
    }

    hitObstacle() {
        this.lives--;
        this.updateUI();
        
        if (this.lives <= 0) {
            this.gameOver();
        }
    }

    collectCoin() {
        this.score += 10;
        this.updateUI();
    }

    updateUI() {
        document.getElementById('score').textContent = Math.floor(this.score);
        document.getElementById('lives').textContent = this.lives;
        document.getElementById('distance').textContent = Math.floor(this.distance);
    }

    gameOver() {
        this.isGameOver = true;
        document.getElementById('final-score').textContent = Math.floor(this.score);
        document.getElementById('game-over').classList.remove('hidden');
    }

    startGame() {
        this.isGameOver = false;
        this.score = 0;
        this.lives = 3;
        this.distance = 0;
        this.speed = 200;
        this.updateUI();
    }

    restartGame() {
        // Clear all obstacles and coins
        this.obstacles.forEach(obstacle => obstacle.destroy());
        this.coins.forEach(coin => coin.destroy());
        this.obstacles = [];
        this.coins = [];
        
        this.startGame();
    }
}

// Game configuration
const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'game-canvas',
    physics: {
        default: 'arcade',
        arcade: {
            gravity: { y: 0 },
            debug: false
        }
    },
    scene: TempleRunGame
};

// Start the game
const game = new Phaser.Game(config);`;
  }

  /**
   * Generate CSS file for Temple Run
   */
  generateTempleRunCSS() {
    return `/* Temple Run Game Styles */
body {
    margin: 0;
    padding: 0;
    font-family: 'Arial', sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

#game-container {
    position: relative;
    border: 3px solid #333;
    border-radius: 10px;
    overflow: hidden;
    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
}

#game-canvas {
    display: block;
}

#game-ui {
    position: absolute;
    top: 10px;
    left: 10px;
    right: 10px;
    display: flex;
    justify-content: space-between;
    color: white;
    font-weight: bold;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.7);
    z-index: 10;
}

#game-ui > div {
    background: rgba(0,0,0,0.5);
    padding: 5px 10px;
    border-radius: 5px;
}

#start-screen, #game-over {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,0.8);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: white;
    text-align: center;
    z-index: 20;
}

#start-screen h1 {
    font-size: 3em;
    margin-bottom: 20px;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.7);
}

#start-screen p {
    font-size: 1.2em;
    margin: 10px 0;
}

#game-over h2 {
    font-size: 2.5em;
    margin-bottom: 20px;
    color: #ff6b6b;
}

button {
    background: #4CAF50;
    color: white;
    border: none;
    padding: 15px 30px;
    font-size: 1.2em;
    border-radius: 5px;
    cursor: pointer;
    margin-top: 20px;
    transition: background 0.3s;
}

button:hover {
    background: #45a049;
}

.hidden {
    display: none !important;
}`;
  }

  /**
   * Generate package.json for game
   */
  generateGamePackageJson() {
    return `{
  "name": "temple-run-game",
  "version": "1.0.0",
  "description": "Temple Run game generated by DreamBuild",
  "main": "game.js",
  "scripts": {
    "start": "python -m http.server 8000",
    "serve": "npx serve ."
  },
  "dependencies": {
    "phaser": "^3.70.0"
  },
  "keywords": ["game", "temple-run", "endless-runner", "phaser"],
  "author": "DreamBuild AI",
  "license": "MIT"
}`;
  }

  /**
   * Generate README for Temple Run
   */
  generateTempleRunREADME() {
    return `# Temple Run Game

A fully playable Temple Run clone generated by DreamBuild AI using Phaser.js.

## Features

- **Endless Runner Gameplay**: Run as far as you can without hitting obstacles
- **Lane Switching**: Use A/D or Arrow Keys to switch between 3 lanes
- **Jumping**: Press W, Up Arrow, or Space to jump over obstacles
- **Sliding**: Press S or Down Arrow to slide under high obstacles
- **Coin Collection**: Collect coins to increase your score
- **Progressive Difficulty**: Game speed increases as you run further

## How to Play

1. **Start the Game**: Click "Start Game" button
2. **Switch Lanes**: Use A/D keys or Left/Right arrows
3. **Jump**: Press W, Up Arrow, or Space
4. **Slide**: Press S or Down Arrow
5. **Collect Coins**: Run into coins to increase score
6. **Avoid Obstacles**: Don't hit obstacles or you'll lose a life

## Controls

- **A/D Keys**: Switch lanes left/right
- **W/Up Arrow/Space**: Jump
- **S/Down Arrow**: Slide
- **Mouse**: Click buttons

## Installation

1. Open \`index.html\` in a web browser
2. Or run a local server:
   \`\`\`bash
   npx serve .
   \`\`\`

## Technical Details

- **Framework**: Phaser.js 3.70.0
- **Physics**: Arcade Physics
- **Graphics**: Canvas-based rendering
- **Input**: Keyboard and Mouse support

## Game Mechanics

- **3 Lanes**: Player can switch between left, center, and right lanes
- **Obstacle Types**: High obstacles (jump over) and low obstacles (slide under)
- **Scoring**: 10 points per coin collected
- **Lives**: Start with 3 lives, lose 1 when hitting obstacles
- **Speed**: Gradually increases based on distance traveled

Enjoy the game! 🎮`;
  }

  /**
   * Get Temple Run instructions
   */
  getTempleRunInstructions() {
    return {
      title: "Temple Run Game",
      description: "A fully playable endless runner game using Phaser.js",
      controls: {
        "Lane Switching": "A/D keys or Left/Right arrows",
        "Jump": "W, Up Arrow, or Space",
        "Slide": "S or Down Arrow"
      },
      features: [
        "3-lane endless runner gameplay",
        "Jump and slide mechanics",
        "Coin collection system",
        "Progressive difficulty",
        "Score and lives tracking",
        "Responsive controls"
      ],
      framework: "Phaser.js",
      difficulty: "Medium"
    };
  }

  // Phaser scene methods
  templeRunPreload() {
    // This will be called by Phaser
  }

  templeRunCreate() {
    // This will be called by Phaser
  }

  templeRunUpdate() {
    // This will be called by Phaser
  }

  /**
   * Generate other game templates
   */
  generateEndlessRunnerTemplate(options = {}) {
    return this.generateTempleRunTemplate(options);
  }

  generatePlatformerTemplate(options = {}) {
    // Implementation for platformer games
    return {
      framework: 'phaser',
      config: {},
      files: {},
      instructions: {}
    };
  }

  generatePuzzleTemplate(options = {}) {
    // Implementation for puzzle games
    return {
      framework: 'phaser',
      config: {},
      files: {},
      instructions: {}
    };
  }

  generateArcadeTemplate(options = {}) {
    // Implementation for arcade games
    return {
      framework: 'phaser',
      config: {},
      files: {},
      instructions: {}
    };
  }
}

export default new GameDevelopmentService();
