// Todo App Initializer - Generated by DreamBuild Built-in AI

document.addEventListener('DOMContentLoaded', () => {
  // Initialize Todo App
  const todoList = new TodoList()
  const addTodo = new AddTodo(todoList)
  
  // Render components
  document.getElementById('todo-list').innerHTML = ''
  document.getElementById('add-todo').innerHTML = ''
  
  todoList.render()
  addTodo.render()
})
