// Game App Initializer - Generated by DreamBuild Built-in AI

document.addEventListener('DOMContentLoaded', () => {
  // Initialize Game App
  const game = new Game()
  
  // Render game
  document.getElementById('game').innerHTML = ''
  game.render()
})
