// RPG Game - Generated by DreamBuild
class RPGGame {
    constructor() {
        this.player = {
            x: 400,
            y: 300,
            health: 100,
            maxHealth: 100,
            level: 1,
            experience: 0,
            inventory: []
        };
        this.isRunning = false;
        this.npcs = [];
        this.items = [];
        
        this.init();
    }

    init() {
        this.createCanvas();
        this.setupEventListeners();
        this.gameLoop();
        console.log('⚔️ RPG Game initialized!');
    }

    createCanvas() {
        const canvas = document.createElement('canvas');
        canvas.id = 'game-canvas';
        canvas.width = 1024;
        canvas.height = 768;
        
        const container = document.getElementById('game-container');
        const existingCanvas = document.getElementById('game-canvas');
        if (existingCanvas) {
            container.replaceChild(canvas, existingCanvas);
        } else {
            container.appendChild(canvas);
        }
        
        this.canvas = canvas;
        this.ctx = canvas.getContext('2d');
    }

    setupEventListeners() {
        document.addEventListener('keydown', (e) => {
            if (!this.isRunning) {
                this.startGame();
                return;
            }
            
            switch(e.code) {
                case 'KeyW':
                case 'ArrowUp':
                    this.movePlayer(0, -5);
                    break;
                case 'KeyS':
                case 'ArrowDown':
                    this.movePlayer(0, 5);
                    break;
                case 'KeyA':
                case 'ArrowLeft':
                    this.movePlayer(-5, 0);
                    break;
                case 'KeyD':
                case 'ArrowRight':
                    this.movePlayer(5, 0);
                    break;
            }
        });

        document.getElementById('start-btn').addEventListener('click', () => {
            this.startGame();
        });
    }

    startGame() {
        this.isRunning = true;
        document.getElementById('game-menu').classList.add('hidden');
        console.log('⚔️ RPG Game started!');
    }

    movePlayer(dx, dy) {
        this.player.x = Math.max(20, Math.min(this.canvas.width - 20, this.player.x + dx));
        this.player.y = Math.max(20, Math.min(this.canvas.height - 20, this.player.y + dy));
    }

    gameLoop() {
        this.update();
        this.draw();
        requestAnimationFrame(() => this.gameLoop());
    }

    update() {
        if (!this.isRunning) return;
    }

    draw() {
        this.ctx.fillStyle = '#228B22';
        this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
        
        this.ctx.fillStyle = '#4169E1';
        this.ctx.fillRect(this.player.x - 10, this.player.y - 10, 20, 20);
        
        this.ctx.fillStyle = 'white';
        this.ctx.font = '16px Arial';
        this.ctx.fillText(`Health: ${this.player.health}/${this.player.maxHealth}`, 10, 30);
        this.ctx.fillText(`Level: ${this.player.level}`, 10, 50);
        this.ctx.fillText(`Experience: ${this.player.experience}`, 10, 70);
    }
}

new RPGGame();